use_frameworks!

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ORCharts_Example' do
  pod 'ORCharts', :path => '../'

  target 'ORCharts_Tests' do
    inherit! :search_paths

    
  end
end
